### ISSUE TITLE
Multiple ratings

### ISSUE THREAD

**Issue by sverin** [fraserxu/ionic-rating#10]
How can I use this directive in a list, i.e. multiple ratings, one per row?
I can't find a way to bind the ng-model to the data.

**Comment by calendee** [comment]
This is how I'm doing it:

```
<div class="item item-text-wrap" ng-repeat="question in feedbackQuestions.ratingQuestions">
  <p>{{question.name}}</p>
  <rating ng-model="question.rating" max="max"></rating>
</div>
```

**Comment by sverin** [comment]
This is how I'm trying to do it, but it won't work.
```
<ion-list>
  <ion-item collection-repeat="favorite in favorites">
    <span>{{favorite.get('name').name}}</span>
    <span class="item-note">
      <rating ng-model="favorite.rating" max="5"></rating>
    </span>
  </ion-item>
</ion-list>
```

**Comment by calendee** [comment]
You can't have `max="5"` in there. The ratings directive is using `max` on it's scope.  So you must put it in your controller's scope:

````
$scope.maxRating = 5;
```

```
<rating ng-model="favorite.rating" max="{{maxRating}}"></rating>
```

Give that a shot.

**Comment by sverin** [comment]
This line of code gives me one empty star:
```
<rating ng-model="favorite.rating" max="{{maxRating}}"></rating>
```
However, this line of code gives me five stars, without rating values
```
<rating ng-model="favorite.rating" max="5"></rating>
```
And I have verified that the value in the scope is set

**Comment by calendee** [comment]
You might want to setup a CodePen sample.  It would be easier to help the.

**Comment by sverin** [comment]
Got it working! Tanks!
