### ISSUE TITLE
How to detect changes?

### ISSUE THREAD

**Issue by sverin** [fraserxu/ionic-rating#11]
How can I detect changes to the rating control?
So that I can save the rating value?

**Comment by calendee** [comment]
The rating value is on your scope.  So, you can $watch it if you need to or use `ng-change`.

**Comment by sverin** [comment]
That's what I hoped for but I can't get it to work.

$watch never triggers since the scope value never change
```
$scope.$watch('rating', function() {
  console.log('value: '+$scope.rating);
});
```

However, ng-change triggers, but the scope value is the same:
```
$scope.change = function() {
  console.log('value: '+$scope.rating);
}
```

**Comment by calendee** [comment]
It's probably because you're using a primitive : `$scope.rating`.

Try this instead (this well solve LOTS of problems with Angular).  You need to understand  this better:

https://github.com/angular/angular.js/wiki/Understanding-Scopes

```
$scope.data = {
  rating :  1,
  max : 5
}

$scope.$watch('rating', function() {
  console.log('value: '+$scope.rating);
});
```

Then in the view use :

```
<rating ng-model="data.rate" max="data.max"></rating>
```

**Comment by calendee** [comment]
Here's a sample : http://codepen.io/calendee/pen/zxygJe

**Comment by sverin** [comment]
Thank you, now it's works great!
