### ISSUE TITLE
Issue with the stars when I integrate them into my project

### ISSUE THREAD

**Issue by YerayRD** [fraserxu/ionic-rating#12]
Hello, first of all thanks for sharing your code. I have tested it in a new empty project and works great. However, when I integrate it into my project the stars dont appear but I know the ul and li elements exists because I can see them using the inspect elements feature of the browser. 

I have attached a image that shows that the elements exist but the stars are not printed. I have tried to use the z-index option in case these were hidden but no luck.

In my index.html I have included the library with the ionic-rating.js and the ionic-rating.css. In the body of the index I have a ng-view that changes dynamically. When I want the stars to appear I do the following, add the controller to the ion-content element and this line of code:  <rating ng-model="rate"  max="max"></rating>. In the app.js, I have integrated 'ionic.rating' and in the controller I initialize it by doing $scope.rate= 3, $scope.max =5. 

Do you have any idea what I am doing wrong? 

Best,
Yeray

![11227286_10153266597274836_1487639086_o](https://cloud.githubusercontent.com/assets/2955387/7649904/90a4f0e8-faf1-11e4-99ac-1285ec2fdac3.jpg)

**Comment by YerayRD** [comment]
I forgot to mention that I had also changed the colour of the stars within the ionic-rating.css. The new colour is yellow and it worked in the empty test I had done previously

**Comment by YerayRD** [comment]
Hello again, I figured it out by myself... there was some problem with the icons... I think they did exist due to different versions of ionic.

**Comment by fraserxu** [comment]
:+1:
