### ISSUE TITLE
Click/tap on icons doesn't work

### ISSUE THREAD

**Issue by karlpower6** [fraserxu/ionic-rating#14]
I could have missed something, but clicking/tapping on the stars doesn't change the $scope.rate value.
The code exists in the page:
```html
<li ng-repeat="r in range track by $index" ng-click="rate($index + 1)" class=""><i class="icon ion-ios-star" ng-class="$index < value &amp;&amp; (r.stateOn || 'ion-ios-star') || (r.stateOff || 'ion-ios-star-outline')"></i></li>
```
I have included the ```<script src="lib/ionic-rating/ionic-rating.js"></script>``` in index.html and added ionic.rating as a dependency in my app.

**Comment by karlpower6** [comment]
Update: It's working fine, just not inside ```<label>``` tag.

**Comment by fraserxu** [comment]
Yes, if you want it work for `label`, I guess you just need to bind the click event on the label instead of `li`.
