### ISSUE TITLE
Not Displaying

### ISSUE THREAD

**Issue by nickrouty** [fraserxu/ionic-rating#15]
I've gone through the steps but am not seeing the ratings come up. Added JS/CSS to my index.html file, required the module in my controller, added the <rating> snippet from the example into my view, but it doesn't come up -- something I may be missing?

**Comment by fraserxu** [comment]
Can you create a simple repo so that I can debug? Can not do anything without seeing the code.

**Comment by nickrouty** [comment]
I went ahead and created my own, it doesn't have as many options, but pretty simple in implementation. Thanks for replying though, I'm sure I was probably just doing something wrong, or my gulp file didn't include something correctly..

```html
<div class="rating">
    <ul>
        <li ng-click="setRating(1);"><i ng-class="order.rating >= 1 ? 'icon ion-android-star' : 'icon ion-android-star-outline'"></i></li>
        <li ng-click="setRating(2);"><i ng-class="order.rating >= 2 ? 'icon ion-android-star' : 'icon ion-android-star-outline'"></i></li>
        <li ng-click="setRating(3);"><i ng-class="order.rating >= 3 ? 'icon ion-android-star' : 'icon ion-android-star-outline'"></i></li>
        <li ng-click="setRating(4);"><i ng-class="order.rating >= 4 ? 'icon ion-android-star' : 'icon ion-android-star-outline'"></i></li>
        <li ng-click="setRating(5);"><i ng-class="order.rating >= 5 ? 'icon ion-android-star' : 'icon ion-android-star-outline'"></i></li>
    </ul>
</div>

**Comment by jahanzebk** [comment]
I am having the exact same problem.
