### ISSUE TITLE
How to enable readonly mode?

### ISSUE THREAD

**Issue by jdmswong** [fraserxu/ionic-rating#17]
Hi Frasier, I see $scope.readonly mentioned in the code, but setting $scope.readonly = true does nothing.  How do I enable read-only?

**Comment by jdmswong** [comment]
Solved!:
added ```readonly="readOnly"``` to rating directive, and ```$scope.readOnly = true;``` to the controller.

**Comment by fraserxu** [comment]
:+1: Maybe I'll put that in the readme file!

**Comment by monsif** [comment]
Hi, this solution is not working for me, when i change readonly from '=?' to 'readOnly' i am getting an error.  fyi i am using  "version": "0.3.0",
