### ISSUE TITLE
error when running in strict-di mode

### ISSUE THREAD

**Issue by ffabreti** [fraserxu/ionic-rating#18]
I'm getting this error: 
https://docs.angularjs.org/error/$injector/strictdi?p0=RatingController

you should annotate your controller so your module can run on strict-di.

change to something like:
`.controller('RatingController', [ '$scope', '$attrs', 'ratingConfig', function($scope, $attrs, ratingConfig) `

don't forget the closing ]

**Comment by mapeveri** [comment]
@fraserxu You can add this?. Thanks!

**Comment by fraserxu** [comment]
Updated! Thanks @mapeveri @ffabreti
