### ISSUE TITLE
bower install ionic-rating 

### ISSUE THREAD

**Issue by galsharir** [fraserxu/ionic-rating#19]
I'm trying to install ionic-rating through bower, but am getting the following error, any workaround?

bower ionic#1.1.0              ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/driftyco/ionic-bower.git", exit code of #128 fatal: Unable to look up github.com (port 9418) (nodename nor servname provided, or not known)

Additional error details:
fatal: Unable to look up github.com (port 9418) (nodename nor servname provided, or not known)

**Comment by fraserxu** [comment]
This maybe a network issue. You may try run it again.
