### ISSUE TITLE
ionic-rating is not injectable after installing with bower 

### ISSUE THREAD

**Issue by shfaizanali** [fraserxu/ionic-rating#3]
angular.module('starter', ['ionic','ionic-rating','starter.controllers', 'starter.services']) 

adding ionic-rating as a dependency gives error and app fails to initiate. Although the js file is copied to 
'ionic-rating': 'www/lib/ionic-rating/ionic-rating.js',

**Comment by bmantoni** [comment]
I'm getting the same error (but haven't misspelled the module). Somewhat new to ionic so maybe another newbie mistake. I have an app.js, and separate js files for each controller.
In the controller I'm trying to use this in, I have:
    angular.module('myapp.controllers', ['ionic.rating']).controller('MyCtrl', function($scope, $stateParams) {
All I did to setup was:
    bower install -S ionic-rating
Confirmed bower.json has dependency added, and ion-rating added to www/lib

Any ideas?

**Comment by bmantoni** [comment]
OK, figured it out. I had to include the js in my index.html:
```<script src="lib/ionic-rating/ionic-rating.js"></script>```
(and the CSS too).

**Comment by Pinsonbavard** [comment]
I can't install ionic-rating, bower gives me bower ENOTFOUND error 
![ionic-rating-error](https://cloud.githubusercontent.com/assets/6134716/9604897/1cb269ec-50b2-11e5-94f6-be2ff962cd3e.PNG)

**Comment by vivek1729** [comment]
I am getting a similar error too. Have installed the module with `bower` and trying to use it in a controller by defining it in the module like so:

      angular.module('tinker', ['ionic.rating']).controller('ActivityCtrl', function($scope,..)


Error I get is :

      error    Uncaught Error: [$injector:modulerr] Failed to instantiate module tinker due to:
           Error: [$injector:unpr] Unknown provider: $stateProvider
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=%24stateProvider

The order of js files getting loaded in my `index.html` is this:


      <script src="js/jquery-1.11.1.min.js" type="text/javascript"></script>
      <script src="js/lib/d3.min.js" language="JavaScript"></script>
      <script src="js/lib/liquidFillGauge.js" language="JavaScript"></script>
     
      <script src="lib/ionic/js/ionic.bundle.js"></script>
      <script src="lib/ionic-rating/ionic-rating.min.js"></script>
      


What am I doing wrong here? Any help is deeply appreciated.
