### ISSUE TITLE
Is anyway to disable the input for display only?

### ISSUE THREAD

**Issue by bbugs280** [fraserxu/ionic-rating#4]
Hi, this is a great directive. I'm using this for displaying an average rating which doesn't allow update. 

Is there a "disabled" attribute?

**Comment by nelsonwck** [comment]
From the source codes, it seems that adding a "readonly" attribute would serve your purpose.

**Comment by zqrt** [comment]
<rating ng-model="snapper.rate" max="max"  readonly="true">

**Comment by fraserxu** [comment]
I've updated how to do it in the readme file, See #17  Closing this one...
