### ISSUE TITLE
Displays only one star

### ISSUE THREAD

**Issue by kim00kim** [fraserxu/ionic-rating#5]
I tried putting it on my app but it only displays one star even if I change the values of $scope.rate and
$scope.max. I downloaded the zip file, copied the 2 js files  in my app, copied the content of ionic-rating.css in my own css and followed the other instructions. Am I missing something?

By the way, I'm using it inside an ionic modal.

**Comment by qnodesign** [comment]
for some reason the max attribute recognizes its value as "max" string, therefore it shows only one.

if you try max="5" or max="10" on the rating tag it will work. I'm trying to find the cause, and fix it

**Comment by qnodesign** [comment]
solution: use ng-max instead of max
