### ISSUE TITLE
Doesn't work when inside a label

### ISSUE THREAD

**Issue by bmantoni** [fraserxu/ionic-rating#6]
The click event doesn't get handled (so the rate function doesn't get invoked) when inside a label, for example:

```
<label class="item item-input item-stacked-label">
    <span class="input-label">Rating</span>
    <rating ng-model="review.rating" max="5"></rating>
</label>```

**Comment by fraserxu** [comment]
I guess you need to prevent the the default event on the label, there's nothing I can do on the module level.

**Comment by TheJetlag** [comment]
Oh wow, please add this to the readme.
